version: '3.5'

volumes:
  nginx-shared:

services:
  nginx:
    image: nginx:alpine
    hostname: nginx
    ports:
      - "8001:8000"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-shared:/nginx
    depends_on:
      - web
    networks:
      - safenetwork

  redis:
    image: redis:alpine
    ports:
      - "6381:6381"
    command:
      - --port 6381
      - --appendonly yes
    networks:
      - safenetwork

  rabbitmq:
    image: rabbitmq:alpine
    networks:
      - safenetwork

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - safenetwork

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    working_dir: /app
    ports:
      - "8888:8888"
    volumes:
      - nginx-shared:/nginx
    command: docker/web/run_web.sh
    networks:
      - safenetwork

  indexer-worker: &worker
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    environment:
      RUN_MIGRATIONS: 1
      WORKER_QUEUES: "default,indexing"
    depends_on:
      - db
      - redis
      - rabbitmq
    command: docker/web/celery/worker/run.sh
    networks:
      - safenetwork

  contracts-tokens-worker:
    <<: *worker
    environment:
      WORKER_QUEUES: "contracts,tokens"
    networks:
      - safenetwork

  notifications-webhooks-worker:
    <<: *worker
    environment:
      WORKER_QUEUES: "notifications,webhooks"
    networks:
      - safenetwork

  scheduler:
    <<: *worker
    command: docker/web/celery/scheduler/run.sh
    networks:
      - safenetwork

  flower:
    <<: *worker
    command: docker/web/celery/flower/run.sh
    ports:
      - "5555:5555"
    networks:
      - safenetwork

networks:
  safenetwork:
    name: safe_network
